-- ============================================================
-- QUICK SEED: Phonics Items (for AdminPhonicsScreen)
-- Run this in Supabase SQL Editor after COMPLETE_SETUP.sql
-- ============================================================

INSERT INTO public.phonics_items (label, icon, bg_color, is_active) VALUES
  ('ba', '🔤', '#4FC3F7', true),
  ('be', '🔤', '#81C784', true),
  ('bi', '🔤', '#4DD0E1', true),
  ('bo', '🔤', '#AED581', true),
  ('bu', '🔤', '#FFCC02', true),
  ('ca', '🔤', '#FF8A65', true),
  ('ce', '🔤', '#BA68C8', true),
  ('ci', '🔤', '#4DB6AC', true),
  ('co', '🔤', '#FFB74D', true),
  ('cu', '🔤', '#F06292', true),
  ('da', '🔤', '#7986CB', true),
  ('de', '🔤', '#4FC3F7', true),
  ('di', '🔤', '#81C784', true),
  ('do', '🔤', '#4DD0E1', true),
  ('du', '🔤', '#AED581', true),
  ('fa', '🔤', '#FFCC02', true),
  ('fe', '🔤', '#FF8A65', true),
  ('fi', '🔤', '#BA68C8', true),
  ('fo', '🔤', '#4DB6AC', true),
  ('fu', '🔤', '#FFB74D', true),
  ('ga', '🔤', '#F06292', true),
  ('ge', '🔤', '#7986CB', true),
  ('gi', '🔤', '#4FC3F7', true),
  ('go', '🔤', '#81C784', true),
  ('gu', '🔤', '#4DD0E1', true),
  ('ha', '🔤', '#AED581', true),
  ('he', '🔤', '#FFCC02', true),
  ('hi', '🔤', '#FF8A65', true),
  ('ho', '🔤', '#BA68C8', true),
  ('hu', '🔤', '#4DB6AC', true),
  ('ch', '🔤', '#FFB74D', true),
  ('sh', '🔤', '#F06292', true),
  ('th', '🔤', '#7986CB', true),
  ('wh', '🔤', '#4FC3F7', true),
  ('ph', '🔤', '#81C784', true),
  ('qu', '🔤', '#4DD0E1', true),
  ('ja', '🔤', '#AED581', true),
  ('je', '🔤', '#FFCC02', true),
  ('ji', '🔤', '#FF8A65', true),
  ('jo', '🔤', '#BA68C8', true),
  ('ju', '🔤', '#4DB6AC', true),
  ('ka', '🔤', '#FFB74D', true),
  ('ke', '🔤', '#F06292', true),
  ('ki', '🔤', '#7986CB', true),
  ('ko', '🔤', '#4FC3F7', true),
  ('ku', '🔤', '#81C784', true),
  ('la', '🔤', '#4DD0E1', true),
  ('le', '🔤', '#AED581', true),
  ('li', '🔤', '#FFCC02', true),
  ('lo', '🔤', '#FF8A65', true)
ON CONFLICT DO NOTHING;
